version: '3.9'

services:
  sellers-api:
    image: ${APP_VERSION:-sellers-api:latest}
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      options:
        max-size: 10m
    container_name: sellers-api
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_DATABASE: sellers-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DB_HOST: postgres-db
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: sellers-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_SELLERS_DB:-/media/schimidt/Arquivos/projetos/kotlin/databases/seller-db}
